const Data=[
    {
        id:1,
        name:"react",
        img:"https://www.pngkey.com/png/full/222-2224685_react-logo-png-transparent-react-logo.png",
        matched:false
    },
    {
        id:2,
        name:"java",
        img:"https://static.vecteezy.com/system/resources/previews/022/100/214/non_2x/java-logo-transparent-free-png.png",
        matched:false
    },
    {
        id:3,
        name:"css",
        img:"https://icon-library.com/images/css3-icon/css3-icon-28.jpg",
        matched:false
    },
    {
        id:4,
        name:"angular",
        img:"https://freepngdesign.com/content/uploads/images/p-1698-1-angular-logo-png-transparent-logo-214688437269.png",
        matched:false
    },
    {
        id:5,
        name:"java",
        img:"https://static.vecteezy.com/system/resources/previews/022/100/214/non_2x/java-logo-transparent-free-png.png",
        matched:false
    },
    
    {
        id:6,
        name:"html",
        img:"https://cdn-icons-png.freepik.com/512/1532/1532556.png",
        matched:false
    },
    {
        id:7,
        name:"react",
        img:"https://www.pngkey.com/png/full/222-2224685_react-logo-png-transparent-react-logo.png",
        matched:false
    },
    {
        id:8,
        name:"javascript",
        img:"https://static.vecteezy.com/system/resources/previews/048/332/149/non_2x/js-icon-transparent-background-free-png.png",
        matched:false
    },
    {
        id:9,
        name:"angular",
        img:"https://freepngdesign.com/content/uploads/images/p-1698-1-angular-logo-png-transparent-logo-214688437269.png",
        matched:false
    },
    {
        id:10,
        name:"html",
        img:"https://cdn-icons-png.freepik.com/512/1532/1532556.png",
        matched:false
    },
    {
        id:11,
        name:"css",
        img:"https://icon-library.com/images/css3-icon/css3-icon-28.jpg",
        matched:false
    },
    
    {
        id:12,
        name:"javascript",
        img:"https://static.vecteezy.com/system/resources/previews/048/332/149/non_2x/js-icon-transparent-background-free-png.png",
        matched:false
    },
]
export default Data